import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Page } from '@/components/Primitives';
import { useOnboarding } from '@/context/OnboardingContext';
import { colors, radius, shadow } from '@/theme';

const meals=[['sunny-outline','Breakfast','Morning fuel'],['restaurant-outline','Lunch','Midday meal'],['moon-outline','Dinner','Evening meal'],['nutrition-outline','Snacks','Between meals'],['water-outline','Drinks','Water & more']];

export default function Dashboard(){
  const{data,calorieTarget}=useOnboarding();
  return <Page>
    <View style={s.top}>
      <View><Text style={s.overline}>SATURDAY · YOUR DAILY PLAN</Text><Text style={s.hello}>Let&apos;s start strong.</Text></View>
      <View style={s.topActions}><Pressable style={s.roundAction}><Ionicons name="notifications-outline" size={19} color={colors.ink}/></Pressable><Pressable accessibilityLabel="Log out" onPress={()=>router.replace('/welcome')} style={s.roundAction}><Ionicons name="log-out-outline" size={19} color={colors.ink}/></Pressable></View>
    </View>

    <View style={s.hero}>
      <View style={s.heroGlow}/><View style={s.heroCircle}/>
      <View style={s.heroTop}><View style={s.todayBadge}><View style={s.badgeDot}/><Text style={s.todayText}>TODAY&apos;S BALANCE</Text></View><Pressable style={s.more}><Ionicons name="ellipsis-horizontal" size={18} color={colors.ink}/></Pressable></View>
      <View style={s.heroMain}><View><Text style={s.big}>{calorieTarget.toLocaleString()}</Text><Text style={s.kcal}>kcal remaining</Text></View><View style={s.ring}><View style={s.ringInner}><Text style={s.ringValue}>0%</Text><Text style={s.ringLabel}>eaten</Text></View></View></View>
      <View style={s.heroStats}><Metric value="0" label="Eaten"/><View style={s.divider}/><Metric value="0" label="Burned"/><View style={s.divider}/><Metric value={calorieTarget.toLocaleString()} label="Daily goal"/></View>
    </View>

    <View style={s.quickRow}>
      <Quick icon="barbell-outline" label="Workout"/><Quick icon="restaurant-outline" label="Meal"/><Quick icon="water-outline" label="Water"/><Quick icon="sync-outline" label="Sync"/>
    </View>

    <View style={s.sectionHead}><View><Text style={s.sectionEyebrow}>LIVE OVERVIEW</Text><Text style={s.sectionTitle}>Daily summary</Text></View><Pressable><Text style={s.link}>View journey</Text></Pressable></View>
    <View style={s.summaryGrid}>
      <View style={[s.summaryCard,s.weightCard]}><View style={s.cardIcon}><Ionicons name="scale-outline" size={20} color={colors.primary}/></View><Text style={s.cardLabel}>CURRENT WEIGHT</Text><Text style={s.cardNumber}>{data.weight}<Text style={s.cardUnit}> kg</Text></Text><Text style={s.cardMeta}>Goal {data.targetWeight} kg</Text><View style={s.line}><View style={[s.lineFill,{width:'24%'}]}/></View></View>
      <View style={[s.summaryCard,s.stepsCard]}><View style={s.cardIconDark}><Ionicons name="footsteps-outline" size={20} color={colors.white}/></View><Text style={[s.cardLabel,{color:'#B7CEC4'}]}>STEPS TODAY</Text><Text style={[s.cardNumber,{color:colors.white}]}>0</Text><Text style={[s.cardMeta,{color:'#B7CEC4'}]}>of {Number(data.steps).toLocaleString()}</Text><View style={[s.line,{backgroundColor:'rgba(255,255,255,.15)'}]}><View style={[s.lineFill,{width:'4%',backgroundColor:colors.lime}]}/></View></View>
    </View>

    <View style={s.quoteCard}><View style={s.quoteIcon}><Ionicons name="sparkles" size={20} color={colors.primaryDark}/></View><View style={{flex:1}}><Text style={s.quote}>Small choices become strong habits.</Text><Text style={s.quoteSub}>Today only needs one good next step.</Text></View><Ionicons name="arrow-forward" size={18} color={colors.primary}/></View>

    <View style={s.sectionHead}><View><Text style={s.sectionEyebrow}>YOUR DIARY</Text><Text style={s.sectionTitle}>Meals & drinks</Text></View><Pressable><Text style={s.link}>View all</Text></Pressable></View>
    <View style={s.meals}>{meals.map(([icon,title,caption],index)=><Pressable key={title} style={[s.meal,index===0&&s.mealFeatured]}><View style={[s.mealIcon,index===0&&s.mealIconFeatured]}><Ionicons name={icon as never} size={20} color={index===0?colors.primaryDark:colors.primary}/></View><View style={{flex:1}}><Text style={s.mealTitle}>{title}</Text><Text style={s.mealCaption}>{caption} · 0 kcal</Text></View><View style={[s.plus,index===0&&s.plusFeatured]}><Ionicons name="add" size={20} color={index===0?colors.primaryDark:colors.white}/></View></Pressable>)}</View>

    <View style={s.nav}><Nav icon="home" label="Home" active/><Nav icon="pie-chart-outline" label="Journey"/><Nav icon="book-outline" label="Diary"/><Nav icon="person-outline" label="Profile"/><View style={s.navAdd}><Ionicons name="add" size={28} color={colors.primaryDark}/></View></View>
  </Page>;
}

function Metric({value,label}:{value:string;label:string}){return <View style={s.metric}><Text style={s.metricValue}>{value}</Text><Text style={s.metricLabel}>{label}</Text></View>}
function Quick({icon,label}:{icon:keyof typeof Ionicons.glyphMap;label:string}){return <Pressable style={s.quick}><View style={s.quickIcon}><Ionicons name={icon} size={19} color={colors.primary}/></View><Text style={s.quickLabel}>{label}</Text></Pressable>}
function Nav({icon,label,active=false}:{icon:keyof typeof Ionicons.glyphMap;label:string;active?:boolean}){return <Pressable style={[s.navItem,active&&s.navItemOn]}><Ionicons name={icon} size={20} color={active?colors.ink:colors.muted}/>{active?<Text style={s.navTextOn}>{label}</Text>:null}</Pressable>}

const s=StyleSheet.create({
  top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:18},overline:{fontSize:8,fontWeight:'900',letterSpacing:1.1,color:colors.primary},hello:{fontSize:27,fontWeight:'900',letterSpacing:-.9,color:colors.ink,marginTop:4},topActions:{flexDirection:'row',gap:7},roundAction:{width:40,height:40,borderRadius:14,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line,alignItems:'center',justifyContent:'center'},
  hero:{minHeight:285,borderRadius:30,padding:20,backgroundColor:'#DDEFC4',overflow:'hidden',marginBottom:11},heroGlow:{position:'absolute',width:210,height:210,borderRadius:105,right:-60,top:-75,backgroundColor:'rgba(255,255,255,.5)'},heroCircle:{position:'absolute',width:140,height:140,borderRadius:70,right:-48,bottom:-65,borderWidth:24,borderColor:'rgba(35,125,90,.08)'},heroTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},todayBadge:{height:28,borderRadius:99,paddingHorizontal:10,backgroundColor:'rgba(255,255,255,.65)',flexDirection:'row',alignItems:'center',gap:6},badgeDot:{width:6,height:6,borderRadius:3,backgroundColor:colors.primary},todayText:{fontSize:8,fontWeight:'900',letterSpacing:.8,color:colors.primaryDark},more:{width:35,height:35,borderRadius:13,backgroundColor:'rgba(255,255,255,.6)',alignItems:'center',justifyContent:'center'},heroMain:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:20},big:{fontSize:48,fontWeight:'900',letterSpacing:-2,color:colors.ink},kcal:{fontSize:12,fontWeight:'700',color:colors.muted,marginTop:1},ring:{width:100,height:100,borderRadius:50,borderWidth:8,borderColor:'rgba(255,255,255,.65)',borderTopColor:colors.primary,transform:[{rotate:'-25deg'}],alignItems:'center',justifyContent:'center'},ringInner:{transform:[{rotate:'25deg'}],alignItems:'center'},ringValue:{fontSize:21,fontWeight:'900',color:colors.ink},ringLabel:{fontSize:9,color:colors.muted},heroStats:{height:62,borderRadius:19,backgroundColor:'rgba(255,255,255,.62)',flexDirection:'row',alignItems:'center',justifyContent:'space-around',marginTop:21},metric:{flex:1,alignItems:'center'},metricValue:{fontSize:14,fontWeight:'900',color:colors.ink},metricLabel:{fontSize:8,color:colors.muted,marginTop:3},divider:{width:1,height:26,backgroundColor:'rgba(35,125,90,.14)'},
  quickRow:{flexDirection:'row',gap:8,marginBottom:25},quick:{flex:1,minWidth:0,height:78,borderRadius:20,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line,alignItems:'center',justifyContent:'center',gap:6},quickIcon:{width:34,height:34,borderRadius:12,backgroundColor:colors.surfaceAlt,alignItems:'center',justifyContent:'center'},quickLabel:{fontSize:9,fontWeight:'800',color:colors.ink},
  sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end',marginBottom:11},sectionEyebrow:{fontSize:8,fontWeight:'900',letterSpacing:1,color:colors.primary},sectionTitle:{fontSize:21,fontWeight:'900',letterSpacing:-.5,color:colors.ink,marginTop:3},link:{fontSize:10,fontWeight:'800',color:colors.primary},summaryGrid:{flexDirection:'row',gap:10,marginBottom:11},summaryCard:{flex:1,minHeight:190,borderRadius:radius.lg,padding:16,overflow:'hidden'},weightCard:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line},stepsCard:{backgroundColor:'#173A2D'},cardIcon:{width:38,height:38,borderRadius:13,backgroundColor:colors.surfaceAlt,alignItems:'center',justifyContent:'center',marginBottom:18},cardIconDark:{width:38,height:38,borderRadius:13,backgroundColor:'rgba(255,255,255,.12)',alignItems:'center',justifyContent:'center',marginBottom:18},cardLabel:{fontSize:8,fontWeight:'900',letterSpacing:.8,color:colors.muted},cardNumber:{fontSize:27,fontWeight:'900',letterSpacing:-.7,color:colors.ink,marginTop:5},cardUnit:{fontSize:12},cardMeta:{fontSize:9,color:colors.muted,marginTop:2},line:{height:5,borderRadius:5,backgroundColor:colors.line,marginTop:15},lineFill:{height:'100%',borderRadius:5,backgroundColor:colors.primary},
  quoteCard:{minHeight:86,borderRadius:radius.lg,backgroundColor:'#F0F1C8',padding:15,flexDirection:'row',alignItems:'center',gap:12,marginBottom:25},quoteIcon:{width:42,height:42,borderRadius:15,backgroundColor:colors.lime,alignItems:'center',justifyContent:'center'},quote:{fontSize:12,fontWeight:'900',color:colors.ink},quoteSub:{fontSize:9,color:colors.muted,marginTop:4},
  meals:{gap:8},meal:{minHeight:68,borderRadius:19,padding:11,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line,flexDirection:'row',alignItems:'center',gap:11},mealFeatured:{backgroundColor:'#E5F0D1',borderColor:'#D2E3B6'},mealIcon:{width:42,height:42,borderRadius:14,backgroundColor:colors.surfaceAlt,alignItems:'center',justifyContent:'center'},mealIconFeatured:{backgroundColor:'rgba(255,255,255,.7)'},mealTitle:{fontSize:13,fontWeight:'900',color:colors.ink},mealCaption:{fontSize:9,color:colors.muted,marginTop:3},plus:{width:34,height:34,borderRadius:12,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'},plusFeatured:{backgroundColor:colors.lime},
  nav:{marginTop:22,paddingVertical:8,paddingLeft:8,paddingRight:62,borderRadius:25,backgroundColor:'#E9ECEA',flexDirection:'row',alignItems:'center',gap:5,alignSelf:'center',borderWidth:1,borderColor:'rgba(255,255,255,.8)',...shadow},navItem:{width:43,height:43,borderRadius:18,backgroundColor:'rgba(255,255,255,.7)',alignItems:'center',justifyContent:'center'},navItemOn:{width:96,flexDirection:'row',gap:8,backgroundColor:colors.white},navTextOn:{fontSize:11,fontWeight:'900',color:colors.ink},navAdd:{position:'absolute',right:7,width:47,height:47,borderRadius:18,backgroundColor:colors.lime,alignItems:'center',justifyContent:'center',...shadow},
});
