import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { BottomBar, Button, Header, Page } from '@/components/Primitives';
import { useOnboarding } from '@/context/OnboardingContext';
import { colors, radius, shadow } from '@/theme';
export default function Plans(){const{data,update}=useOnboarding();return <Page><Header onBack={()=>router.back()} title="Choose how you want to start" subtitle="Your core plan is available for free. Upgrade only if the extra guidance feels useful."/><Plan title="Free" price="$0" caption="Everything you need to begin" selected={data.plan==='free'} onPress={()=>update({plan:'free'})} features={['Daily calories and weight goals','Lebanese food logging','Weight and activity progress','Custom meals and favorites']}/><Plan title="Plus" price="$4.99" caption="More guidance, less planning" selected={data.plan==='plus'} onPress={()=>update({plan:'plus'})} recommended features={['Everything in Free','Advanced progress insights','Flexible-day planning','Personalized meal suggestions']}/><Text style={s.fine}>Pricing is a preview for product design and is not charged in this first build.</Text><BottomBar><Button label={data.plan==='free'?'Continue with Free':'Continue with Plus'} icon="arrow-forward" onPress={()=>router.push('/auth')}/></BottomBar></Page>}
function Plan({title,price,caption,features,selected,onPress,recommended=false}:{title:string;price:string;caption:string;features:string[];selected:boolean;onPress:()=>void;recommended?:boolean}){return <Pressable onPress={onPress} style={[s.plan,selected&&s.planOn]}>{recommended?<View style={s.ribbon}><Text style={s.ribbonText}>MOST POPULAR</Text></View>:null}<View style={s.planTop}><View><Text style={s.planTitle}>{title}</Text><Text style={s.caption}>{caption}</Text></View><View style={{alignItems:'flex-end'}}><Text style={s.price}>{price}</Text><Text style={s.month}>{price==='$0'?'forever':'/ month'}</Text></View></View><View style={s.rule}/>{features.map(x=><View key={x} style={s.feature}><Ionicons name="checkmark-circle" size={18} color={colors.primary}/><Text style={s.featureText}>{x}</Text></View>)}<View style={[s.select,selected&&s.selectOn]}><Text style={[s.selectText,selected&&s.selectTextOn]}>{selected?'Selected':'Choose plan'}</Text></View></Pressable>}
const s=StyleSheet.create({plan:{backgroundColor:colors.surface,borderRadius:radius.lg,borderWidth:1.5,borderColor:colors.line,padding:19,marginBottom:14,overflow:'hidden',...shadow},planOn:{borderColor:colors.primary,backgroundColor:'#FBFFFC'},ribbon:{position:'absolute',right:0,top:0,backgroundColor:colors.lime,paddingHorizontal:12,paddingVertical:6,borderBottomLeftRadius:12},ribbonText:{fontSize:9,fontWeight:'900',letterSpacing:.7,color:colors.primaryDark},planTop:{flexDirection:'row',justifyContent:'space-between',marginBottom:13},planTitle:{fontSize:22,fontWeight:'900',color:colors.ink},caption:{fontSize:11,color:colors.muted,marginTop:3},price:{fontSize:22,fontWeight:'900',color:colors.ink},month:{fontSize:10,color:colors.muted},rule:{height:1,backgroundColor:colors.line,marginBottom:13},feature:{flexDirection:'row',gap:9,alignItems:'center',marginBottom:9},featureText:{fontSize:12,color:colors.ink,fontWeight:'600'},select:{height:43,borderRadius:14,backgroundColor:colors.surfaceAlt,alignItems:'center',justifyContent:'center',marginTop:6},selectOn:{backgroundColor:colors.primary},selectText:{fontWeight:'800',fontSize:13,color:colors.primary},selectTextOn:{color:colors.white},fine:{fontSize:10,lineHeight:15,color:colors.muted,textAlign:'center',paddingHorizontal:20}});
