import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { BottomBar, Button, Header, Input, Option, Page } from '@/components/Primitives';
import { Activity, Goal, useOnboarding } from '@/context/OnboardingContext';
import { colors, radius } from '@/theme';

const weekdays = ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
const fullDays: Record<string,string> = { Mon:'Monday',Tue:'Tuesday',Wed:'Wednesday',Thu:'Thursday',Fri:'Friday',Sat:'Saturday',Sun:'Sunday' };
const routines = ['Full body','Upper / lower','Push / pull / legs','Strength training','Cardio focused'];

export default function Setup() {
  const { data, update } = useOnboarding();
  const [step,setStep] = useState(1);
  const total = 8;
  const next = () => step === total ? router.push('/analyzing') : setStep(step+1);
  const back = () => step === 1 ? router.back() : setStep(step-1);
  const toggle = (key:'flexibleDays'|'gymDays', value:string) => { const list=data[key]; update({[key]:list.includes(value)?list.filter(x=>x!==value):[...list,value]} as never); };
  const content = () => {
    if(step===1) return <><Header step={step} total={total} onBack={back} title="Let us start with you" subtitle="These details help us estimate a starting point. You can change them later."/><Input label="Age" suffix="years" keyboardType="number-pad" value={data.age} onChangeText={(age)=>update({age})}/><View style={styles.two}><View style={{flex:1}}><Input label="Height" suffix="cm" keyboardType="number-pad" value={data.height} onChangeText={(height)=>update({height})}/></View><View style={{flex:1}}><Input label="Current weight" suffix="kg" keyboardType="decimal-pad" value={data.weight} onChangeText={(weight)=>update({weight})}/></View></View><Text style={styles.label}>Biological sex</Text><View style={styles.two}><Pressable onPress={()=>update({sex:'female'})} style={[styles.choice,data.sex==='female'&&styles.choiceOn]}><Ionicons name="female" size={22} color={data.sex==='female'?colors.white:colors.primary}/><Text style={[styles.choiceText,data.sex==='female'&&styles.choiceTextOn]}>Female</Text></Pressable><Pressable onPress={()=>update({sex:'male'})} style={[styles.choice,data.sex==='male'&&styles.choiceOn]}><Ionicons name="male" size={22} color={data.sex==='male'?colors.white:colors.primary}/><Text style={[styles.choiceText,data.sex==='male'&&styles.choiceTextOn]}>Male</Text></Pressable></View></>;
    if(step===2) return <><Header step={step} total={total} onBack={back} title="What's your main goal?" subtitle="We'll shape your calorie and activity guidance around this."/>{([{v:'lose',t:'Lose weight',d:'Create a realistic calorie deficit',i:'trending-down'},{v:'maintain',t:'Maintain weight',d:'Build consistent everyday habits',i:'remove'},{v:'gain',t:'Gain weight',d:'Increase intake gradually and intentionally',i:'trending-up'}] as const).map(x=><Option key={x.v} title={x.t} description={x.d} icon={x.i} selected={data.goal===x.v} onPress={()=>update({goal:x.v as Goal})}/>)}</>;
    if(step===3) return <><Header step={step} total={total} onBack={back} title="Define your destination" subtitle="Your timeline helps us understand the pace you have in mind."/><Input label="Target weight" suffix="kg" keyboardType="decimal-pad" value={data.targetWeight} onChangeText={(targetWeight)=>update({targetWeight})}/><Input label="Journey duration" suffix="months" keyboardType="number-pad" value={data.durationMonths} onChangeText={(durationMonths)=>update({durationMonths})}/><View style={styles.notice}><Ionicons name="shield-checkmark" size={21} color={colors.primary}/><Text style={styles.noticeText}>If the requested pace is too aggressive, we'll suggest a safer timeline.</Text></View></>;
    if(step===4) return <><Header step={step} total={total} onBack={back} title="How active are you now?" subtitle="Choose the option that reflects most of your week."/>{([{v:'sedentary',t:'Mostly sedentary',d:'Desk-based day, little structured movement'},{v:'light',t:'Lightly active',d:'Some walking or exercise 1-2 days/week'},{v:'moderate',t:'Moderately active',d:'Exercise or active movement 3-4 days/week'},{v:'active',t:'Very active',d:'Hard exercise or active work most days'},{v:'veryActive',t:'Athlete level',d:'Intense training, often twice a day'}] as const).map(x=><Option key={x.v} title={x.t} description={x.d} selected={data.activity===x.v} onPress={()=>update({activity:x.v as Activity})}/>)}</>;
    if(step===5) return <><Header step={step} total={total} onBack={back} title="Your everyday movement" subtitle="An estimate is enough. Connected health data can refine this later."/><Input label="Average daily steps" suffix="steps" keyboardType="number-pad" value={data.steps} onChangeText={(steps)=>update({steps})}/><View style={styles.steps}><Ionicons name="footsteps" size={34} color={colors.primary}/><View><Text style={styles.stepsTitle}>{Number(data.steps||0).toLocaleString()} steps</Text><Text style={styles.stepsSub}>Your current daily estimate</Text></View></View></>;
    if(step===6) return <><Header step={step} total={total} onBack={back} title="Make room for real life" subtitle="Would you like a higher-calorie flexible meal in your weekly plan?"/><Option title="Yes, include flexible meals" description="We'll account for them in your weekly target" icon="restaurant" selected={data.flexibleMeals} onPress={()=>update({flexibleMeals:true})}/><Option title="No, keep every day consistent" description="The same target across the week" icon="calendar" selected={!data.flexibleMeals} onPress={()=>update({flexibleMeals:false,flexibleDays:[]})}/>{data.flexibleMeals?<><Text style={styles.label}>Preferred day</Text><DayPicker selected={data.flexibleDays} onToggle={(d)=>{ if(data.flexibleDays.length<3||data.flexibleDays.includes(d)) toggle('flexibleDays',d); }}/><Text style={styles.helper}>Choose up to three days. We recommend starting with one.</Text></>:null}</>;
    if(step===7) return <><Header step={step} total={total} onBack={back} title="Do you train at a gym?" subtitle="We'll adapt your activity view and training-day guidance."/><Option title="Yes, I train" description="Add my usual schedule" icon="barbell" selected={data.gym} onPress={()=>update({gym:true})}/><Option title="Not right now" description="I can add this later" icon="walk" selected={!data.gym} onPress={()=>update({gym:false,gymDays:[],routine:''})}/>{data.gym?<><Text style={styles.label}>Training days</Text><DayPicker selected={data.gymDays} onToggle={(d)=>toggle('gymDays',d)}/><Text style={styles.label}>Routine</Text><View style={styles.chips}>{routines.map(r=><Pressable key={r} onPress={()=>update({routine:r})} style={[styles.chip,data.routine===r&&styles.chipOn]}><Text style={[styles.chipText,data.routine===r&&styles.chipTextOn]}>{r}</Text></Pressable>)}</View></>:null}</>;
    return <><Header step={step} total={total} onBack={back} title="One last detail" subtitle="Do you currently take any gym or nutrition supplements? This is optional."/><Text style={styles.label}>Select any you currently use</Text>{['Protein powder','Creatine','Pre-workout','Vitamins','Omega-3'].map(s=><Option key={s} title={s} selected={data.supplements.includes(s)} onPress={()=>update({supplements:data.supplements.includes(s)?data.supplements.filter(x=>x!==s):[...data.supplements,s]})}/>) }<Text style={styles.helper}>This is for tracking only. The app will not prescribe supplements or dosages.</Text></>;
  };
  return <Page>{content()}<BottomBar><Button label={step===total?'Create my recommendation':'Continue'} icon="arrow-forward" disabled={step===1&&!data.sex} onPress={next}/></BottomBar></Page>;
}
function DayPicker({selected,onToggle}:{selected:string[];onToggle:(day:string)=>void}) { return <View style={styles.days}>{weekdays.map(d=><Pressable key={d} onPress={()=>onToggle(fullDays[d])} style={[styles.day,selected.includes(fullDays[d])&&styles.dayOn]}><Text style={[styles.dayText,selected.includes(fullDays[d])&&styles.dayTextOn]}>{d}</Text></Pressable>)}</View>; }
const styles=StyleSheet.create({two:{flexDirection:'row',gap:12},label:{fontSize:13,fontWeight:'800',color:colors.ink,marginBottom:9,marginTop:3},choice:{flex:1,minHeight:70,borderRadius:radius.md,borderWidth:1.5,borderColor:colors.line,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center',gap:5},choiceOn:{backgroundColor:colors.primary,borderColor:colors.primary},choiceText:{fontWeight:'800',color:colors.ink},choiceTextOn:{color:colors.white},notice:{padding:15,borderRadius:radius.md,backgroundColor:colors.surfaceAlt,flexDirection:'row',gap:11,alignItems:'center'},noticeText:{flex:1,fontSize:12,lineHeight:18,color:colors.muted},steps:{padding:22,borderRadius:radius.lg,backgroundColor:colors.surfaceAlt,flexDirection:'row',alignItems:'center',gap:18,marginTop:8},stepsTitle:{fontSize:24,fontWeight:'900',color:colors.ink},stepsSub:{fontSize:12,color:colors.muted,marginTop:2},days:{flexDirection:'row',gap:6,marginBottom:8},day:{flex:1,aspectRatio:1,borderRadius:12,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line,alignItems:'center',justifyContent:'center'},dayOn:{backgroundColor:colors.primary,borderColor:colors.primary},dayText:{fontSize:11,fontWeight:'800',color:colors.muted},dayTextOn:{color:colors.white},helper:{fontSize:11,lineHeight:17,color:colors.muted,marginTop:5},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{paddingVertical:10,paddingHorizontal:13,borderRadius:99,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line},chipOn:{backgroundColor:colors.primary,borderColor:colors.primary},chipText:{fontSize:12,fontWeight:'700',color:colors.ink},chipTextOn:{color:colors.white}});
